import Head from 'next/head'
import { Inter } from '@next/font/google'
import Todo from './componenets/Todo'
import { useTodoID } from './lib/hooks'
import { useState } from 'react'
import {DragDropContext} from "react-beautiful-dnd"
import {BiLogOut} from "react-icons/bi"

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Henosis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen'>
        <div className='flex flex-col h-full'>
          <div className='sideBar'>
            <span className='flex items-center'>
            <img src="a8e2979dbeb6e9faeaf2a655de812109.jpg" alt="profile_picture" className='profile_picture peer' />
            <h1 className='opacity-0 text-white mt-1 ml-5 peer-hover:opacity-100 peer-hover:translate-x-1 duration-150'>Welcome, Mr Tsai</h1>
            </span>
            <span className='icon-wrapper group'><BiLogOut className='text-gray-300 pr-2 w-10 h-10 group-hover:translate-x-[-.25rem] duration-150'/></span>
          </div>
            <div className='w-full lg:flex md:flex'>
              <Todo />
            </div>
        </div>
      </main>
    </>
  )
}
